### login
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "qwer1234!"
}

> {%
client.global.set("access_token", response.body.data.accessToken)
client.global.set("refresh_token", response.body.data.refreshToken)
 %}

### Test
GET localhost:8080/api/auth/test
Authorization: Bearer {{access_token}}
