
### 회원가입
POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "qwer1234!",
  "intro": "intro",
  "nickname": "nickname"
}

### 회원탈퇴
POST localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "password": "qwer1234!"
}


